CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          email VARCHAR(512) NOT NULL UNIQUE
        );
        CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          description VARCHAR(1024) NOT NULL,
          available BOOLEAN NOT NULL,
          owner_id BIGINT NOT NULL,
          request_id BIGINT,
          CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS bookings (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          start_date TIMESTAMP NOT NULL,
          end_date TIMESTAMP NOT NULL,
          item_id BIGINT NOT NULL,
          booker_id BIGINT NOT NULL,
          status VARCHAR(50) NOT NULL,
          CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id),
          CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS comments (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          text VARCHAR(1024) NOT NULL,
          item_id BIGINT NOT NULL,
          author_id BIGINT NOT NULL,
          created TIMESTAMP NOT NULL,
          CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES items(id),
          CONSTRAINT fk_comment_user FOREIGN KEY (author_id) REFERENCES users(id)
        );